package cloud.benchflow.testmanager.exceptions;

/**
 * @author Jesper Findahl (jesper.findahl@gmail.com) created on 15.02.17.
 */
public class UserIDAlreadyExistsException extends Exception {
}
